/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Image;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import personajes.Arquero;
import personajes.Dragon;
import personajes.Guerrero;
import personajes.Mago;
import personajes.Personaje;
import personajes.Personaje.Tipo;

/**
 *
 * @author Alumnos_IBT
 */
public class FrmNuevoPersonaje extends javax.swing.JFrame {

    Personaje p;

    public FrmNuevoPersonaje() {
        initComponents();
        DefaultComboBoxModel model = new DefaultComboBoxModel(Tipo.values());
        model.insertElementAt("Selecciona", 0);
        cboTipo.setModel(model);
        cboTipo.setSelectedIndex(0);
        lblPoder.setVisible(false);
        txtPoder.setVisible(false);

        ImageIcon cardOriginalIcon = new javax.swing.ImageIcon(getClass().getResource("/gui/img/Card.png"));
        Image cardResizedImage = cardOriginalIcon.getImage().getScaledInstance(lblCard.getWidth(), lblCard.getHeight(), Image.SCALE_SMOOTH);
        lblCard.setIcon(new ImageIcon(cardResizedImage));

        panPreview.setVisible(false);

//        lblCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/Card400x400.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panPreview = new javax.swing.JLayeredPane();
        btnAtacar = new javax.swing.JButton();
        lblPuntosPoder = new javax.swing.JLabel();
        lblPuntosVida = new javax.swing.JLabel();
        lblPoderPreview = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblCard = new javax.swing.JLabel();
        panNuevo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cboTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtNivel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVida = new javax.swing.JTextField();
        lblPoder = new javax.swing.JLabel();
        txtPoder = new javax.swing.JTextField();
        btnVer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nuevo Personaje");
        setMaximumSize(new java.awt.Dimension(500, 500));

        panPreview.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtacar.setBackground(new java.awt.Color(255, 153, 102));
        btnAtacar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAtacar.setText("A");
        btnAtacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtacarActionPerformed(evt);
            }
        });
        panPreview.add(btnAtacar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 50, 40));

        lblPuntosPoder.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPuntosPoder.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntosPoder.setText("99");
        panPreview.add(lblPuntosPoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, 40));

        lblPuntosVida.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPuntosVida.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntosVida.setText("100");
        panPreview.add(lblPuntosVida, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, -1, 30));

        lblPoderPreview.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblPoderPreview.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPoderPreview.setText("Poder");
        panPreview.add(lblPoderPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 170, 40));

        lblTipo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTipo.setText("Tipo");
        panPreview.add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 170, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Puntos de Vida");
        panPreview.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 170, 40));

        lblNivel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNivel.setForeground(new java.awt.Color(255, 255, 204));
        lblNivel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNivel.setText("55");
        panPreview.setLayer(lblNivel, javax.swing.JLayeredPane.PALETTE_LAYER);
        panPreview.add(lblNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 60, 60));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(255, 255, 204));
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("Nombre");
        panPreview.setLayer(lblNombre, javax.swing.JLayeredPane.PALETTE_LAYER);
        panPreview.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 150, 50));

        lblCard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/img/Card400x400.png"))); // NOI18N
        lblCard.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panPreview.add(lblCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 400, 400));

        panNuevo.setBorder(javax.swing.BorderFactory.createTitledBorder("Nuevo Personaje"));
        panNuevo.setMaximumSize(new java.awt.Dimension(500, 500));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Tipo:");

        cboTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTipoActionPerformed(evt);
            }
        });

        jLabel3.setText("Nivel:");

        jLabel4.setText("Puntos de Vida: ");

        lblPoder.setText("Poder:");

        btnVer.setText("Ver");
        btnVer.setEnabled(false);
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panNuevoLayout = new javax.swing.GroupLayout(panNuevo);
        panNuevo.setLayout(panNuevoLayout);
        panNuevoLayout.setHorizontalGroup(
            panNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre)
                    .addComponent(cboTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panNuevoLayout.createSequentialGroup()
                        .addGroup(panNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVida, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(txtNivel)))
                    .addComponent(lblPoder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPoder)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panNuevoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVer)))
                .addContainerGap())
        );
        panNuevoLayout.setVerticalGroup(
            panNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panNuevoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panNuevoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPoder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPoder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVer)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        txaOutput.setColumns(20);
        txaOutput.setRows(5);
        jScrollPane1.setViewportView(txaOutput);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panPreview, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        String nombre = txtNombre.getText();
        int nivel = Integer.parseInt(txtNivel.getText());
        int vida = Integer.parseInt(txtVida.getText());
        int poder = Integer.parseInt(txtPoder.getText());
        Tipo tipoPersonaje = (Tipo) cboTipo.getSelectedItem();
        switch (tipoPersonaje) {
            case Arquero:
                p = new Arquero(poder, nombre, nivel, vida);

                break;
            case Dragon:
                p = new Dragon(poder, nombre, nivel, vida);
                break;
            case Guerrero:
                p = new Guerrero(poder, nombre, nivel, vida);
                break;
            case Mago:
                p = new Mago(poder, nombre, nivel, vida);
                break;
        }

        lblNombre.setText(p.getNombre());
        lblNivel.setText(p.getNivel() + "");
        lblPuntosVida.setText(p.getPuntosVida() + "");
        lblPuntosPoder.setText(poder + "");

        panPreview.setVisible(true);

    }//GEN-LAST:event_btnVerActionPerformed

    private void cboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTipoActionPerformed
        if (cboTipo.getSelectedIndex() == 0) {
            lblPoder.setVisible(false);
            txtPoder.setVisible(false);
            btnVer.setEnabled(false);

        } else {
            Tipo tipoPersonaje = (Tipo) cboTipo.getSelectedItem();

            switch (tipoPersonaje) {
                case Arquero:
                    lblPoder.setText("Precisión: ");
                    lblPoderPreview.setText("Precisión");
                    break;
                case Dragon:
                    lblPoder.setText("Daño Fuego: ");
                    lblPoderPreview.setText("Daño Fuego");
                    break;
                case Guerrero:
                    lblPoder.setText("Fuerza: ");
                    lblPoderPreview.setText("Fuerza");
                case Mago:
                    lblPoder.setText("Poder Mágico: ");
                    lblPoderPreview.setText("Poder Mágico");
                default:
                    lblPoder.setVisible(false);
                    txtPoder.setVisible(false);
                    btnVer.setEnabled(false);
            }
            lblPoder.setVisible(true);
            txtPoder.setVisible(true);
            btnVer.setEnabled(true);

        }
    }//GEN-LAST:event_cboTipoActionPerformed

    private void btnAtacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtacarActionPerformed
        String historial = txaOutput.getText();
        historial += p.atacar() + "\n";
        txaOutput.setText(historial);
    }//GEN-LAST:event_btnAtacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNuevoPersonaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmNuevoPersonaje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtacar;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox<Tipo> cboTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCard;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPoder;
    private javax.swing.JLabel lblPoderPreview;
    private javax.swing.JLabel lblPuntosPoder;
    private javax.swing.JLabel lblPuntosVida;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JPanel panNuevo;
    private javax.swing.JLayeredPane panPreview;
    private javax.swing.JTextArea txaOutput;
    private javax.swing.JTextField txtNivel;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPoder;
    private javax.swing.JTextField txtVida;
    // End of variables declaration//GEN-END:variables
}
